// Generates packages/shared/src/generated/abi.ts from compiled artifacts (single source for API + web).
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const names = ["DeviceRegistry", "EvidenceRegistry", "AssetLifecycle"];
const out = {};
for (const n of names) {
  const p = path.join(__dirname, "..", "artifacts", "contracts", `${n}.sol`, `${n}.json`);
  out[n] = JSON.parse(fs.readFileSync(p, "utf8")).abi;
}
const abiVersion = crypto.createHash("sha256").update(JSON.stringify(out)).digest("hex").slice(0, 16);
const dir = path.join(__dirname, "..", "..", "shared", "src", "generated");
fs.mkdirSync(dir, { recursive: true });
let ts = `// AUTO-GENERATED by packages/contracts/scripts/export-abi.cjs — do not edit.\nexport const ABI_VERSION = "${abiVersion}";\n`;
for (const n of names) ts += `export const ${n}Abi = ${JSON.stringify(out[n])} as const;\n`;
fs.writeFileSync(path.join(dir, "abi.ts"), ts);
console.log(`exported ABIs (abiVersion ${abiVersion})`);
