// AUTO-GENERATED by firmware/tools/gen_pins.mjs from pins/profiles.json — DO NOT EDIT.
// Reference board: ESP32-DevKitC (ESP32-WROOM-32, classic ESP32)
#pragma once

#define TM_CAPBIT_RFID (1UL << 0)
#define TM_CAPBIT_DHT22 (1UL << 1)
#define TM_CAPBIT_ULTRASONIC (1UL << 2)
#define TM_CAPBIT_IR (1UL << 3)
#define TM_CAPBIT_FLAME (1UL << 4)
#define TM_CAPBIT_MQ135 (1UL << 5)
#define TM_CAPBIT_RAIN (1UL << 6)
#define TM_CAPBIT_SOIL (1UL << 7)
#define TM_CAPBIT_DS18B20 (1UL << 8)
#define TM_CAPBIT_LDR (1UL << 9)
#define TM_CAPBIT_PIR (1UL << 10)
#define TM_CAPBIT_GPS (1UL << 11)
#define TM_CAPBIT_POT (1UL << 12)
#define TM_CAPBIT_SERVO (1UL << 13)
#define TM_CAPBIT_RELAY (1UL << 14)
#define TM_CAPBIT_PUMP (1UL << 15)
#define TM_CAPBIT_RGB (1UL << 16)
#define TM_CAPBIT_VIBRATION (1UL << 17)
#define TM_CAPBIT_SD (1UL << 18)

#if defined(TM_PROFILE_CORE) + defined(TM_PROFILE_ENV) + defined(TM_PROFILE_WET) + defined(TM_PROFILE_ACT) + defined(TM_PROFILE_FULL_A) + defined(TM_PROFILE_FULL_B) + defined(TM_PROFILE_NEWRRO_MIN) + defined(TM_PROFILE_NEWRRO_FULL) != 1
#error "Define exactly one TM_PROFILE_<name> (see platformio.ini)"
#endif

#ifdef TM_PROFILE_CORE
#define TM_PROFILE_NAME "CORE"
#define HAS_RFID 1
#define HAS_DHT22 1
#define HAS_ULTRASONIC 1
#define HAS_IR 1
#define HAS_FLAME 1
#define HAS_SERVO 1
#define HAS_RGB 1
#define TM_BOARD "esp32"
#define TM_CAPS (TM_CAPBIT_RFID | TM_CAPBIT_DHT22 | TM_CAPBIT_ULTRASONIC | TM_CAPBIT_IR | TM_CAPBIT_FLAME | TM_CAPBIT_SERVO | TM_CAPBIT_RGB)
#define PIN_SPI_SCK 18 // RC522 RFID SCK
#define PIN_SPI_MISO 19 // RC522 RFID MISO
#define PIN_SPI_MOSI 23 // RC522 RFID MOSI
#define PIN_RFID_SS 21 // RC522 RFID SDA/SS (chip select)
#define PIN_RFID_RST 22 // RC522 RFID RST
#define PIN_DHT 4 // DHT22 DATA
#define PIN_US_TRIG 26 // HC-SR04 TRIG
#define PIN_US_ECHO 34 // HC-SR04 ECHO
#define PIN_IR 35 // IR obstacle module DO (active LOW)
#define PIN_FLAME 39 // Flame module DO (active LOW)
#define PIN_SERVO 13 // MG995/MG996R servo PWM
#define PIN_LED_R 25 // RGB LED (common anode) R
#define PIN_LED_G 33 // RGB LED (common anode) G
#define PIN_LED_B 32 // RGB LED (common anode) B
#define PIN_MANUAL_STOP 0 // BOOT button (on board) manual stop
#endif

#ifdef TM_PROFILE_ENV
#define TM_PROFILE_NAME "ENV"
#define HAS_DHT22 1
#define HAS_MQ135 1
#define HAS_LDR 1
#define HAS_PIR 1
#define HAS_FLAME 1
#define HAS_POT 1
#define HAS_RGB 1
#define TM_BOARD "esp32"
#define TM_CAPS (TM_CAPBIT_DHT22 | TM_CAPBIT_MQ135 | TM_CAPBIT_LDR | TM_CAPBIT_PIR | TM_CAPBIT_FLAME | TM_CAPBIT_POT | TM_CAPBIT_RGB)
#define PIN_DHT 4 // DHT22 DATA
#define PIN_MQ135 36 // MQ135 AO
#define PIN_LDR 39 // LDR divider mid-point
#define PIN_PIR 27 // HC-SR501 PIR OUT
#define PIN_FLAME 35 // Flame module DO (active LOW)
#define PIN_POT 34 // 10 kΩ potentiometer wiper
#define PIN_LED_R 25 // RGB LED (common anode) R
#define PIN_LED_G 33 // RGB LED (common anode) G
#define PIN_LED_B 32 // RGB LED (common anode) B
#endif

#ifdef TM_PROFILE_WET
#define TM_PROFILE_NAME "WET"
#define HAS_RAIN 1
#define HAS_SOIL 1
#define HAS_DS18B20 1
#define HAS_ULTRASONIC 1
#define HAS_IR 1
#define HAS_RGB 1
#define TM_BOARD "esp32"
#define TM_CAPS (TM_CAPBIT_RAIN | TM_CAPBIT_SOIL | TM_CAPBIT_DS18B20 | TM_CAPBIT_ULTRASONIC | TM_CAPBIT_IR | TM_CAPBIT_RGB)
#define PIN_RAIN 36 // Rain-drop module AO
#define PIN_SOIL 39 // Soil-moisture module AO
#define PIN_WET_PWR 16 // Wet-sensor power switch VCC enable
#define PIN_ONEWIRE 4 // DS18B20 probe DQ
#define PIN_US_TRIG 26 // HC-SR04 TRIG
#define PIN_US_ECHO 34 // HC-SR04 ECHO
#define PIN_IR 35 // IR obstacle module DO
#define PIN_LED_R 25 // RGB LED (common anode) R
#define PIN_LED_G 33 // RGB LED (common anode) G
#define PIN_LED_B 32 // RGB LED (common anode) B
#endif

#ifdef TM_PROFILE_ACT
#define TM_PROFILE_NAME "ACT"
#define HAS_RELAY 1
#define HAS_PUMP 1
#define HAS_SERVO 1
#define HAS_VIBRATION 1
#define HAS_GPS 1
#define HAS_SD 1
#define HAS_POT 1
#define HAS_RGB 1
#define TM_BOARD "esp32"
#define TM_CAPS (TM_CAPBIT_RELAY | TM_CAPBIT_PUMP | TM_CAPBIT_SERVO | TM_CAPBIT_VIBRATION | TM_CAPBIT_GPS | TM_CAPBIT_SD | TM_CAPBIT_POT | TM_CAPBIT_RGB)
#define PIN_RELAY 27 // Relay module (5 V, optocoupler) IN
#define PIN_SERVO 13 // MG995/MG996R servo PWM
#define PIN_VIBRATION 17 // Coin vibration motor driver gate/base
#define PIN_GPS_RX 16 // NEO-6M GPS TX → ESP RX2
#define PIN_SPI_SCK 18 // microSD module (SPI) SCK
#define PIN_SPI_MISO 19 // microSD module (SPI) MISO
#define PIN_SPI_MOSI 23 // microSD module (SPI) MOSI
#define PIN_SD_CS 4 // microSD module (SPI) CS
#define PIN_POT 34 // 10 kΩ potentiometer wiper
#define PIN_LED_R 25 // RGB LED (common anode) R
#define PIN_LED_G 33 // RGB LED (common anode) G
#define PIN_LED_B 32 // RGB LED (common anode) B
#define PIN_MANUAL_STOP 0 // BOOT button (on board) manual stop
#endif

#ifdef TM_PROFILE_FULL_A
#define TM_PROFILE_NAME "FULL_A"
#define HAS_RFID 1
#define HAS_DHT22 1
#define HAS_ULTRASONIC 1
#define HAS_IR 1
#define HAS_FLAME 1
#define HAS_MQ135 1
#define HAS_RAIN 1
#define HAS_SOIL 1
#define HAS_DS18B20 1
#define TM_BOARD "esp32"
#define TM_CAPS (TM_CAPBIT_RFID | TM_CAPBIT_DHT22 | TM_CAPBIT_ULTRASONIC | TM_CAPBIT_IR | TM_CAPBIT_FLAME | TM_CAPBIT_MQ135 | TM_CAPBIT_RAIN | TM_CAPBIT_SOIL | TM_CAPBIT_DS18B20)
#define PIN_SPI_SCK 18 // RC522 RFID SCK
#define PIN_SPI_MISO 19 // RC522 RFID MISO
#define PIN_SPI_MOSI 23 // RC522 RFID MOSI
#define PIN_RFID_SS 21 // RC522 RFID SDA/SS
#define PIN_RFID_RST 22 // RC522 RFID RST
#define PIN_DHT 4 // DHT22 DATA
#define PIN_US_TRIG 26 // HC-SR04 TRIG
#define PIN_US_ECHO 34 // HC-SR04 ECHO
#define PIN_IR 35 // IR obstacle module DO
#define PIN_FLAME 39 // Flame module DO
#define PIN_MQ135 36 // MQ135 AO
#define PIN_RAIN 32 // Rain-drop module AO
#define PIN_SOIL 33 // Soil-moisture module AO
#define PIN_WET_PWR 25 // Wet-sensor power switch VCC enable
#define PIN_ONEWIRE 27 // DS18B20 probe DQ
#endif

#ifdef TM_PROFILE_FULL_B
#define TM_PROFILE_NAME "FULL_B"
#define HAS_RELAY 1
#define HAS_PUMP 1
#define HAS_SERVO 1
#define HAS_VIBRATION 1
#define HAS_GPS 1
#define HAS_SD 1
#define HAS_RGB 1
#define HAS_POT 1
#define HAS_PIR 1
#define HAS_LDR 1
#define TM_BOARD "esp32"
#define TM_CAPS (TM_CAPBIT_RELAY | TM_CAPBIT_PUMP | TM_CAPBIT_SERVO | TM_CAPBIT_VIBRATION | TM_CAPBIT_GPS | TM_CAPBIT_SD | TM_CAPBIT_RGB | TM_CAPBIT_POT | TM_CAPBIT_PIR | TM_CAPBIT_LDR)
#define PIN_RELAY 27 // Relay module (5 V, optocoupler) IN
#define PIN_SERVO 13 // MG995/MG996R servo PWM
#define PIN_VIBRATION 17 // Coin vibration motor driver
#define PIN_GPS_RX 16 // NEO-6M GPS TX → ESP RX2
#define PIN_SPI_SCK 18 // microSD module (SPI) SCK
#define PIN_SPI_MISO 19 // microSD module (SPI) MISO
#define PIN_SPI_MOSI 23 // microSD module (SPI) MOSI
#define PIN_SD_CS 4 // microSD module (SPI) CS
#define PIN_LED_R 25 // RGB LED (common anode) R
#define PIN_LED_G 33 // RGB LED (common anode) G
#define PIN_LED_B 32 // RGB LED (common anode) B
#define PIN_POT 34 // 10 kΩ potentiometer wiper
#define PIN_PIR 35 // HC-SR501 PIR OUT
#define PIN_LDR 39 // LDR divider
#define PIN_MANUAL_STOP 0 // BOOT button (on board) manual stop
#endif

#ifdef TM_PROFILE_NEWRRO_MIN
#define TM_PROFILE_NAME "NEWRRO_MIN"
#define HAS_RFID 1
#define HAS_DS18B20 1
#define HAS_LDR 1
#define HAS_RGB 1
#define HAS_IR 1
#define TM_RGB_ACTIVE_HIGH 1
#define TM_S3_PULLS 1
#define TM_BOARD "esp32s3"
#define TM_CAPS (TM_CAPBIT_RFID | TM_CAPBIT_DS18B20 | TM_CAPBIT_LDR | TM_CAPBIT_RGB | TM_CAPBIT_IR)
#define PIN_RFID_RST 15 // RC522 RFID (Newrro RFID port) RST
#define PIN_SPI_MISO 16 // RC522 RFID (Newrro RFID port) MISO
#define PIN_SPI_MOSI 17 // RC522 RFID (Newrro RFID port) MOSI
#define PIN_SPI_SCK 18 // RC522 RFID (Newrro RFID port) SCK
#define PIN_RFID_SS 3 // RC522 RFID (Newrro RFID port) SDA/SS
#define PIN_ONEWIRE 1 // DS18B20 probe (TEMP port) DQ
#define PIN_LDR 4 // LDR (onboard) divider
#define PIN_LED_R 5 // RGB LED (onboard, common cathode) R
#define PIN_LED_G 6 // RGB LED (onboard, common cathode) G
#define PIN_LED_B 7 // RGB LED (onboard, common cathode) B
#define PIN_IR 12 // IR obstacle module OUT (active LOW)
#endif

#ifdef TM_PROFILE_NEWRRO_FULL
#define TM_PROFILE_NAME "NEWRRO_FULL"
#define HAS_RFID 1
#define HAS_DS18B20 1
#define HAS_LDR 1
#define HAS_RGB 1
#define HAS_IR 1
#define HAS_FLAME 1
#define HAS_DHT22 1
#define TM_RGB_ACTIVE_HIGH 1
#define TM_S3_PULLS 1
#define TM_BOARD "esp32s3"
#define TM_CAPS (TM_CAPBIT_RFID | TM_CAPBIT_DS18B20 | TM_CAPBIT_LDR | TM_CAPBIT_RGB | TM_CAPBIT_IR | TM_CAPBIT_FLAME | TM_CAPBIT_DHT22)
#define PIN_RFID_RST 15 // RC522 RFID (Newrro RFID port) RST
#define PIN_SPI_MISO 16 // RC522 RFID (Newrro RFID port) MISO
#define PIN_SPI_MOSI 17 // RC522 RFID (Newrro RFID port) MOSI
#define PIN_SPI_SCK 18 // RC522 RFID (Newrro RFID port) SCK
#define PIN_RFID_SS 3 // RC522 RFID (Newrro RFID port) SDA/SS
#define PIN_ONEWIRE 1 // DS18B20 probe (TEMP port) DQ
#define PIN_LDR 4 // LDR (onboard) divider
#define PIN_LED_R 5 // RGB LED (onboard, common cathode) R
#define PIN_LED_G 6 // RGB LED (onboard, common cathode) G
#define PIN_LED_B 7 // RGB LED (onboard, common cathode) B
#define PIN_IR 12 // IR obstacle module OUT (active LOW)
#define PIN_FLAME 13 // Flame module DO (active LOW)
#define PIN_DHT 14 // DHT22 DATA
#endif
