// npm run firmware:secrets -- [--device ESP32-017] [--wifi "SSID" --pass "PASSWORD"] [--url http://IP:4000]
// Writes firmware/include/secrets.h from .local/devices.json (git-ignored) so nobody has to copy keys by hand.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { networkInterfaces } from "node:os";
import { ROOT, PORTS, c } from "./lib.mjs";
const arg = (k, d = "") => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? process.argv[i + 1] ?? d : d; };
const device = arg("device", "ESP32-017");
const file = resolve(ROOT, ".local/devices.json");
if (!existsSync(file)) { console.error(c.err("No .local/devices.json yet — run `npm run dev` once so the demo devices are created.")); process.exit(1); }
const s = JSON.parse(readFileSync(file, "utf8"))[device];
if (!s) { console.error(c.err(`Device ${device} not found in .local/devices.json`)); process.exit(1); }
const ip = Object.values(networkInterfaces()).flat().find((i) => i?.family === "IPv4" && !i.internal)?.address ?? "192.168.1.20";
const url = arg("url", `http://${ip}:${PORTS.api}`);
const q = (v) => JSON.stringify(v);
writeFileSync(resolve(ROOT, "firmware/include/secrets.h"), `// Generated by npm run firmware:secrets — DO NOT COMMIT (git-ignored).
#pragma once
#define TM_DEVICE_ID   ${q(device)}
#define TM_KEY_VERSION ${s.keyVersion}
#define TM_SECRET_HEX  ${q(s.secretHex)}
#define TM_WIFI_SSID   ${q(arg("wifi"))}
#define TM_WIFI_PASS   ${q(arg("pass"))}
#define TM_BACKEND_URL ${q(url)}
`);
console.log(c.ok(`✔ firmware/include/secrets.h written for ${device} (key v${s.keyVersion})`));
console.log(arg("wifi") ? `  Wi-Fi "${arg("wifi")}" → ${url}  (set API_HOST=0.0.0.0 in .env)` : "  Transport: USB serial bridge (no Wi-Fi configured)");
