#!/usr/bin/env node
// Generates firmware/include/pins_generated.h, docs/WIRING_TABLES.md and docs/wiring/<PROFILE>.svg from
// firmware/pins/profiles.json, and validates every profile. `--check` validates + verifies generated files are current.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const FW = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = resolve(FW, "..");
const cfg = JSON.parse(readFileSync(resolve(FW, "pins/profiles.json"), "utf8"));
const BOARDS = cfg.boards;
const B = BOARDS.esp32;
const CAP_BITS = ["RFID", "DHT22", "ULTRASONIC", "IR", "FLAME", "MQ135", "RAIN", "SOIL", "DS18B20", "LDR", "PIR", "GPS", "POT", "SERVO", "RELAY", "PUMP", "RGB", "VIBRATION", "SD"];

export function validate(name, p) {
  const B = BOARDS[p.board ?? "esp32"] ?? BOARDS.esp32;
  const errs = [], seen = new Map(), syms = new Map();
  for (const x of p.pins) {
    if (x.gpio === null) continue;
    const where = `${name}: ${x.component} ${x.signal} → GPIO${x.gpio}`;
    if (B.forbidden.includes(x.gpio)) errs.push(`${where}: GPIO6–11 are wired to SPI flash`);
    if (B.inputOnly.includes(x.gpio) && x.dir !== "in") errs.push(`${where}: input-only pin used as ${x.dir}`);
    if (B.strapping.includes(x.gpio) && !x.allowStrapping) errs.push(`${where}: strapping pin driven externally`);
    const analog = x.level === "analog" || /^AO|wiper|divider/.test(x.signal) || /0–5 V → /.test(x.level);
    if (analog && !B.adc1.includes(x.gpio)) errs.push(`${where}: analog input must use ADC1 (ADC2 unusable with Wi-Fi)`);
    if (/5 V → 3\.3 V|0–5 V/.test(x.level) && !/divider|shifter/i.test(x.circuit)) errs.push(`${where}: 5 V signal without divider/level shifter`);
    const prev = seen.get(x.gpio);
    if (prev && !(prev.bus && prev.bus === x.bus && prev.signal === x.signal)) errs.push(`${where}: conflicts with ${prev.component} ${prev.signal}`);
    if (!prev) seen.set(x.gpio, x);
    if (syms.has(x.symbol) && syms.get(x.symbol) !== x.gpio) errs.push(`${where}: symbol ${x.symbol} mapped to two pins`);
    syms.set(x.symbol, x.gpio);
  }
  for (const c of p.caps) if (!CAP_BITS.includes(c)) errs.push(`${name}: unknown capability ${c}`);
  return errs;
}

function header() {
  let h = `// AUTO-GENERATED by firmware/tools/gen_pins.mjs from pins/profiles.json — DO NOT EDIT.\n// Reference board: ${B.name}\n#pragma once\n\n`;
  CAP_BITS.forEach((c, i) => (h += `#define TM_CAPBIT_${c} (1UL << ${i})\n`));
  const names = Object.keys(cfg.profiles);
  h += `\n#if ${names.map((n) => `defined(TM_PROFILE_${n})`).join(" + ")} != 1\n#error "Define exactly one TM_PROFILE_<name> (see platformio.ini)"\n#endif\n`;
  for (const [n, p] of Object.entries(cfg.profiles)) {
    h += `\n#ifdef TM_PROFILE_${n}\n#define TM_PROFILE_NAME "${n}"\n`;
    for (const c of p.caps) h += `#define HAS_${c} 1\n`;
    for (const [k, v] of Object.entries(p.defines ?? {})) h += `#define ${k} ${v}\n`;
    h += `#define TM_BOARD "${p.board ?? "esp32"}"\n`;
    h += `#define TM_CAPS (${p.caps.map((c) => `TM_CAPBIT_${c}`).join(" | ")})\n`;
    const done = new Set();
    for (const x of p.pins) if (x.gpio !== null && !done.has(x.symbol)) { done.add(x.symbol); h += `#define ${x.symbol} ${x.gpio} // ${x.component} ${x.signal}\n`; }
    h += `#endif\n`;
  }
  return h;
}

function tables() {
  let md = `<!-- AUTO-GENERATED by firmware/tools/gen_pins.mjs from firmware/pins/profiles.json — edit the JSON, not this file. -->\n# Wiring tables (generated)\n\nReference board: **${B.name}** · logic ${B.logic}.\n\n${B.notes}\n\n`;
  for (const [n, p] of Object.entries(cfg.profiles)) {
    md += `## Profile ${n}\n\nBoard: **${BOARDS[p.board ?? "esp32"].name}**\n\n${p.description}\n\nCapabilities: ${p.caps.join(", ")} · Diagram: [wiring/${n}.svg](wiring/${n}.svg)\n\n| Component | Signal | Dir | ESP32 GPIO | Supply | Logic level | Required circuit | Firmware symbol |\n|---|---|---|---|---|---|---|---|\n`;
    for (const x of p.pins) md += `| ${x.component} | ${x.signal} | ${x.dir} | ${x.gpio ?? "—"}${x.bus ? ` (${x.bus}, shared)` : ""} | ${x.supply} | ${x.level} | ${x.circuit} | \`${x.symbol}\` |\n`;
    md += "\n";
  }
  return md;
}

function svg(n, p) {
  const pins = p.pins.filter((x) => x.gpio !== null);
  const comps = [...new Set(p.pins.map((x) => x.component))];
  const rowH = 22, H = Math.max(pins.length, comps.length * 2) * rowH + 90, W = 980;
  const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;");
  let s = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family="ui-monospace,Menlo,monospace" font-size="11">\n<rect width="100%" height="100%" fill="#0a1022"/>\n<text x="20" y="28" fill="#22d3ee" font-size="14" font-weight="bold">TRUSTMESH ${n} — generated from pins/profiles.json</text>\n`;
  s += `<rect x="20" y="50" width="200" height="${pins.length * rowH + 20}" rx="10" fill="#131d3b" stroke="#22d3ee"/><text x="30" y="${66}" fill="#e6eaf7" font-weight="bold">${(p.board ?? "esp32") === "esp32s3" ? "Newrro ESP32-S3" : "ESP32-DevKitC (WROOM-32)"}</text>\n`;
  const compY = {}; comps.forEach((c, i) => (compY[c] = 60 + i * rowH * 2));
  comps.forEach((c) => (s += `<rect x="640" y="${compY[c] - 12}" width="320" height="${rowH * 1.6}" rx="6" fill="#131d3b" stroke="#2a3a68"/><text x="650" y="${compY[c] + 4}" fill="#e6eaf7">${esc(c)}</text>\n`));
  pins.forEach((x, i) => {
    const y = 84 + i * rowH, color = x.dir === "in" ? "#34d399" : x.dir === "out" ? "#fbbf24" : "#c084fc";
    s += `<text x="30" y="${y + 4}" fill="#a9b4d6">GPIO${x.gpio}</text><text x="95" y="${y + 4}" fill="#7d8bb5">${esc(x.symbol)}</text>`;
    s += `<path d="M220 ${y} C 420 ${y}, 440 ${compY[x.component]}, 640 ${compY[x.component]}" stroke="${color}" fill="none" stroke-width="1.4"/>`;
    s += `<text x="430" y="${(y + compY[x.component]) / 2 - 3}" fill="${color}" font-size="9">${esc(x.signal)}${/divider|shifter|NPN|transistor/i.test(x.circuit) ? " ⚠ circuit" : ""}</text>\n`;
  });
  s += `<text x="20" y="${H - 14}" fill="#7d8bb5">green = input · amber = output · violet = bidirectional · "⚠ circuit" = divider/driver required (see WIRING_TABLES.md). Power & ground rails omitted; external supplies share GND.</text>\n</svg>\n`;
  return s;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
function main() {
const check = process.argv.includes("--check");
  let errors = [];
  for (const [n, p] of Object.entries(cfg.profiles)) errors = errors.concat(validate(n, p));
  const covered = new Set(Object.values(cfg.profiles).flatMap((p) => p.caps));
  const missing = CAP_BITS.filter((c) => !covered.has(c));
  if (missing.length) errors.push(`capabilities with no profile: ${missing.join(", ")}`);
  const outputs = { [resolve(FW, "include/pins_generated.h")]: header(), [resolve(ROOT, "docs/WIRING_TABLES.md")]: tables() };
  for (const [n, p] of Object.entries(cfg.profiles)) outputs[resolve(ROOT, `docs/wiring/${n}.svg`)] = svg(n, p);
  if (check) {
    for (const [f, c] of Object.entries(outputs)) if (!existsSync(f) || readFileSync(f, "utf8") !== c) errors.push(`${f.replace(ROOT + "/", "")} is stale — run npm run pins`);
  } else {
    for (const [f, c] of Object.entries(outputs)) { mkdirSync(dirname(f), { recursive: true }); writeFileSync(f, c); }
  }
  if (errors.length) { console.error("✖ pin configuration errors:\n  " + errors.join("\n  ")); process.exit(1); }
  console.log(`✔ pins valid for ${Object.keys(cfg.profiles).length} profiles; all 19 capabilities covered${check ? "; generated files current" : "; generated header, tables, diagrams"}`);
  
}
